### ISSUE TITLE
Don’t “forget” search results each time

### ISSUE THREAD

**Issue by tomayac** [jeffposnick/yt-playlist-notifier#4]
There are two ways to improve upon the status quo:
- Don’t navigate away from the search results when the user clicks a bell icon. (Preferred)
- Don’t reset the search results when the user comes back to the search tab.

**Comment by jeffposnick** [comment]
Fixed by https://github.com/jeffposnick/yt-playlist-notifier/commit/ed5865d98d5fbd64d5341cdaa160ac8cebf55541

Thanks to the previous change, it was pretty straightforward to just stay on the search page, since now the results will toggle between subscribe/unsubscribe.
